# Generated by Django 6.0.2 on 2026-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tutor', 'Tutor'), ('guardian', 'Guardian')], db_index=True, default='guardian', max_length=20),
        ),
    ]
